std::vector<AvroPattern> makePatterns() {
    return {
        AvroPattern{"bhl", "ভ্ল", {
        }},
        AvroPattern{"psh", "পশ", {
        }},
        AvroPattern{"bdh", "ব্ধ", {
        }},
        AvroPattern{"bj", "ব্জ", {
        }},
        AvroPattern{"bd", "ব্দ", {
        }},
        AvroPattern{"bb", "ব্ব", {
        }},
        AvroPattern{"bl", "ব্ল", {
        }},
        AvroPattern{"bh", "ভ", {
        }},
        AvroPattern{"vl", "ভ্ল", {
        }},
        AvroPattern{"b", "ব", {
        }},
        AvroPattern{"v", "ভ", {
        }},
        AvroPattern{"cNG", "চ্ঞ", {
        }},
        AvroPattern{"cch", "চ্ছ", {
        }},
        AvroPattern{"cc", "চ্চ", {
        }},
        AvroPattern{"ch", "ছ", {
        }},
        AvroPattern{"c", "চ", {
        }},
        AvroPattern{"dhn", "ধ্ন", {
        }},
        AvroPattern{"dhm", "ধ্ম", {
        }},
        AvroPattern{"dgh", "দ্ঘ", {
        }},
        AvroPattern{"ddh", "দ্ধ", {
        }},
        AvroPattern{"dbh", "দ্ভ", {
        }},
        AvroPattern{"dv", "দ্ভ", {
        }},
        AvroPattern{"dm", "দ্ম", {
        }},
        AvroPattern{"DD", "ড্ড", {
        }},
        AvroPattern{"Dh", "ঢ", {
        }},
        AvroPattern{"dh", "ধ", {
        }},
        AvroPattern{"dg", "দ্গ", {
        }},
        AvroPattern{"dd", "দ্দ", {
        }},
        AvroPattern{"D", "ড", {
        }},
        AvroPattern{"d", "দ", {
        }},
        AvroPattern{"...", "...", {
        }},
        AvroPattern{".`", ".", {
        }},
        AvroPattern{"..", "।।", {
        }},
        AvroPattern{".", "।", {
        }},
        AvroPattern{"ghn", "ঘ্ন", {
        }},
        AvroPattern{"Ghn", "ঘ্ন", {
        }},
        AvroPattern{"gdh", "গ্ধ", {
        }},
        AvroPattern{"Gdh", "গ্ধ", {
        }},
        AvroPattern{"gN", "গ্ণ", {
        }},
        AvroPattern{"GN", "গ্ণ", {
        }},
        AvroPattern{"gn", "গ্ন", {
        }},
        AvroPattern{"Gn", "গ্ন", {
        }},
        AvroPattern{"gm", "গ্ম", {
        }},
        AvroPattern{"Gm", "গ্ম", {
        }},
        AvroPattern{"gl", "গ্ল", {
        }},
        AvroPattern{"Gl", "গ্ল", {
        }},
        AvroPattern{"gg", "জ্ঞ", {
        }},
        AvroPattern{"GG", "জ্ঞ", {
        }},
        AvroPattern{"Gg", "জ্ঞ", {
        }},
        AvroPattern{"gG", "জ্ঞ", {
        }},
        AvroPattern{"gh", "ঘ", {
        }},
        AvroPattern{"Gh", "ঘ", {
        }},
        AvroPattern{"g", "গ", {
        }},
        AvroPattern{"G", "গ", {
        }},
        AvroPattern{"hN", "হ্ণ", {
        }},
        AvroPattern{"hn", "হ্ন", {
        }},
        AvroPattern{"hm", "হ্ম", {
        }},
        AvroPattern{"hl", "হ্ল", {
        }},
        AvroPattern{"h", "হ", {
        }},
        AvroPattern{"jjh", "জ্ঝ", {
        }},
        AvroPattern{"jNG", "জ্ঞ", {
        }},
        AvroPattern{"jh", "ঝ", {
        }},
        AvroPattern{"jj", "জ্জ", {
        }},
        AvroPattern{"j", "জ", {
        }},
        AvroPattern{"J", "জ", {
        }},
        AvroPattern{"kkhN", "ক্ষ্ণ", {
        }},
        AvroPattern{"kShN", "ক্ষ্ণ", {
        }},
        AvroPattern{"kkhm", "ক্ষ্ম", {
        }},
        AvroPattern{"kShm", "ক্ষ্ম", {
        }},
        AvroPattern{"kxN", "ক্ষ্ণ", {
        }},
        AvroPattern{"kxm", "ক্ষ্ম", {
        }},
        AvroPattern{"kkh", "ক্ষ", {
        }},
        AvroPattern{"kSh", "ক্ষ", {
        }},
        AvroPattern{"ksh", "কশ", {
        }},
        AvroPattern{"kx", "ক্ষ", {
        }},
        AvroPattern{"kk", "ক্ক", {
        }},
        AvroPattern{"kT", "ক্ট", {
        }},
        AvroPattern{"kt", "ক্ত", {
        }},
        AvroPattern{"kl", "ক্ল", {
        }},
        AvroPattern{"ks", "ক্স", {
        }},
        AvroPattern{"kh", "খ", {
        }},
        AvroPattern{"k", "ক", {
        }},
        AvroPattern{"lbh", "ল্ভ", {
        }},
        AvroPattern{"ldh", "ল্ধ", {
        }},
        AvroPattern{"lkh", "লখ", {
        }},
        AvroPattern{"lgh", "লঘ", {
        }},
        AvroPattern{"lph", "লফ", {
        }},
        AvroPattern{"lk", "ল্ক", {
        }},
        AvroPattern{"lg", "ল্গ", {
        }},
        AvroPattern{"lT", "ল্ট", {
        }},
        AvroPattern{"lD", "ল্ড", {
        }},
        AvroPattern{"lp", "ল্প", {
        }},
        AvroPattern{"lv", "ল্ভ", {
        }},
        AvroPattern{"lm", "ল্ম", {
        }},
        AvroPattern{"ll", "ল্ল", {
        }},
        AvroPattern{"lb", "ল্ব", {
        }},
        AvroPattern{"l", "ল", {
        }},
        AvroPattern{"mth", "ম্থ", {
        }},
        AvroPattern{"mph", "ম্ফ", {
        }},
        AvroPattern{"mbh", "ম্ভ", {
        }},
        AvroPattern{"mpl", "মপ্ল", {
        }},
        AvroPattern{"mn", "ম্ন", {
        }},
        AvroPattern{"mp", "ম্প", {
        }},
        AvroPattern{"mv", "ম্ভ", {
        }},
        AvroPattern{"mm", "ম্ম", {
        }},
        AvroPattern{"ml", "ম্ল", {
        }},
        AvroPattern{"mb", "ম্ব", {
        }},
        AvroPattern{"mf", "ম্ফ", {
        }},
        AvroPattern{"m", "ম", {
        }},
        AvroPattern{"0", "০", {
        }},
        AvroPattern{"1", "১", {
        }},
        AvroPattern{"2", "২", {
        }},
        AvroPattern{"3", "৩", {
        }},
        AvroPattern{"4", "৪", {
        }},
        AvroPattern{"5", "৫", {
        }},
        AvroPattern{"6", "৬", {
        }},
        AvroPattern{"7", "৭", {
        }},
        AvroPattern{"8", "৮", {
        }},
        AvroPattern{"9", "৯", {
        }},
        AvroPattern{"NgkSh", "ঙ্ক্ষ", {
        }},
        AvroPattern{"Ngkkh", "ঙ্ক্ষ", {
        }},
        AvroPattern{"NGch", "ঞ্ছ", {
        }},
        AvroPattern{"Nggh", "ঙ্ঘ", {
        }},
        AvroPattern{"Ngkh", "ঙ্খ", {
        }},
        AvroPattern{"NGjh", "ঞ্ঝ", {
        }},
        AvroPattern{"ngOU", "ঙ্গৌ", {
        }},
        AvroPattern{"ngOI", "ঙ্গৈ", {
        }},
        AvroPattern{"Ngkx", "ঙ্ক্ষ", {
        }},
        AvroPattern{"NGc", "ঞ্চ", {
        }},
        AvroPattern{"nch", "ঞ্ছ", {
        }},
        AvroPattern{"njh", "ঞ্ঝ", {
        }},
        AvroPattern{"ngh", "ঙ্ঘ", {
        }},
        AvroPattern{"Ngk", "ঙ্ক", {
        }},
        AvroPattern{"Ngx", "ঙ্ষ", {
        }},
        AvroPattern{"Ngg", "ঙ্গ", {
        }},
        AvroPattern{"Ngm", "ঙ্ম", {
        }},
        AvroPattern{"NGj", "ঞ্জ", {
        }},
        AvroPattern{"ndh", "ন্ধ", {
        }},
        AvroPattern{"nTh", "ন্ঠ", {
        }},
        AvroPattern{"NTh", "ণ্ঠ", {
        }},
        AvroPattern{"nth", "ন্থ", {
        }},
        AvroPattern{"nkh", "ঙ্খ", {
        }},
        AvroPattern{"ngo", "ঙ্গ", {
        }},
        AvroPattern{"nga", "ঙ্গা", {
        }},
        AvroPattern{"ngi", "ঙ্গি", {
        }},
        AvroPattern{"ngI", "ঙ্গী", {
        }},
        AvroPattern{"ngu", "ঙ্গু", {
        }},
        AvroPattern{"ngU", "ঙ্গূ", {
        }},
        AvroPattern{"nge", "ঙ্গে", {
        }},
        AvroPattern{"ngO", "ঙ্গো", {
        }},
        AvroPattern{"NDh", "ণ্ঢ", {
        }},
        AvroPattern{"nsh", "নশ", {
        }},
        AvroPattern{"Ngr", "ঙর", {
        }},
        AvroPattern{"NGr", "ঞর", {
        }},
        AvroPattern{"ngr", "ংর", {
        }},
        AvroPattern{"nj", "ঞ্জ", {
        }},
        AvroPattern{"Ng", "ঙ", {
        }},
        AvroPattern{"NG", "ঞ", {
        }},
        AvroPattern{"nk", "ঙ্ক", {
        }},
        AvroPattern{"ng", "ং", {
        }},
        AvroPattern{"nn", "ন্ন", {
        }},
        AvroPattern{"NN", "ণ্ণ", {
        }},
        AvroPattern{"Nn", "ণ্ন", {
        }},
        AvroPattern{"nm", "ন্ম", {
        }},
        AvroPattern{"Nm", "ণ্ম", {
        }},
        AvroPattern{"nd", "ন্দ", {
        }},
        AvroPattern{"nT", "ন্ট", {
        }},
        AvroPattern{"NT", "ণ্ট", {
        }},
        AvroPattern{"nD", "ন্ড", {
        }},
        AvroPattern{"ND", "ণ্ড", {
        }},
        AvroPattern{"nt", "ন্ত", {
        }},
        AvroPattern{"ns", "ন্স", {
        }},
        AvroPattern{"nc", "ঞ্চ", {
        }},
        AvroPattern{"n", "ন", {
        }},
        AvroPattern{"N", "ণ", {
        }},
        AvroPattern{"OI`", "ৈ", {
        }},
        AvroPattern{"OU`", "ৌ", {
        }},
        AvroPattern{"O`", "ো", {
        }},
        AvroPattern{"OI", "ৈ", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
            }, "ঐ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "ঐ"},
        }},
        AvroPattern{"OU", "ৌ", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
            }, "ঔ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "ঔ"},
        }},
        AvroPattern{"O", "ো", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
            }, "ও"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "ও"},
        }},
        AvroPattern{"phl", "ফ্ল", {
        }},
        AvroPattern{"pT", "প্ট", {
        }},
        AvroPattern{"pt", "প্ত", {
        }},
        AvroPattern{"pn", "প্ন", {
        }},
        AvroPattern{"pp", "প্প", {
        }},
        AvroPattern{"pl", "প্ল", {
        }},
        AvroPattern{"ps", "প্স", {
        }},
        AvroPattern{"ph", "ফ", {
        }},
        AvroPattern{"fl", "ফ্ল", {
        }},
        AvroPattern{"f", "ফ", {
        }},
        AvroPattern{"p", "প", {
        }},
        AvroPattern{"rri`", "ৃ", {
        }},
        AvroPattern{"rri", "ৃ", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
            }, "ঋ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "ঋ"},
        }},
        AvroPattern{"rrZ", "রর‍্য", {
        }},
        AvroPattern{"rry", "রর‍্য", {
        }},
        AvroPattern{"rZ", "র‍্য", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", false},
                AvroMatchRule{"prefix", "exact", "r", true},
                AvroMatchRule{"prefix", "exact", "y", true},
                AvroMatchRule{"prefix", "exact", "w", true},
                AvroMatchRule{"prefix", "exact", "x", true},
            }, "্র্য"},
        }},
        AvroPattern{"ry", "র‍্য", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", false},
                AvroMatchRule{"prefix", "exact", "r", true},
                AvroMatchRule{"prefix", "exact", "y", true},
                AvroMatchRule{"prefix", "exact", "w", true},
                AvroMatchRule{"prefix", "exact", "x", true},
            }, "্র্য"},
        }},
        AvroPattern{"rr", "রর", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "vowel", "", true},
                AvroMatchRule{"suffix", "exact", "r", true},
                AvroMatchRule{"suffix", "punctuation", "", true},
            }, "র্"},
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", false},
                AvroMatchRule{"prefix", "exact", "r", true},
            }, "্রর"},
        }},
        AvroPattern{"Rg", "ড়্গ", {
        }},
        AvroPattern{"Rh", "ঢ়", {
        }},
        AvroPattern{"R", "ড়", {
        }},
        AvroPattern{"r", "র", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", false},
                AvroMatchRule{"prefix", "exact", "r", true},
                AvroMatchRule{"prefix", "exact", "y", true},
                AvroMatchRule{"prefix", "exact", "w", true},
                AvroMatchRule{"prefix", "exact", "x", true},
                AvroMatchRule{"prefix", "exact", "Z", true},
            }, "্র"},
        }},
        AvroPattern{"shch", "শ্ছ", {
        }},
        AvroPattern{"ShTh", "ষ্ঠ", {
        }},
        AvroPattern{"Shph", "ষ্ফ", {
        }},
        AvroPattern{"Sch", "শ্ছ", {
        }},
        AvroPattern{"skl", "স্ক্ল", {
        }},
        AvroPattern{"skh", "স্খ", {
        }},
        AvroPattern{"sth", "স্থ", {
        }},
        AvroPattern{"sph", "স্ফ", {
        }},
        AvroPattern{"shc", "শ্চ", {
        }},
        AvroPattern{"sht", "শ্ত", {
        }},
        AvroPattern{"shn", "শ্ন", {
        }},
        AvroPattern{"shm", "শ্ম", {
        }},
        AvroPattern{"shl", "শ্ল", {
        }},
        AvroPattern{"Shk", "ষ্ক", {
        }},
        AvroPattern{"ShT", "ষ্ট", {
        }},
        AvroPattern{"ShN", "ষ্ণ", {
        }},
        AvroPattern{"Shp", "ষ্প", {
        }},
        AvroPattern{"Shf", "ষ্ফ", {
        }},
        AvroPattern{"Shm", "ষ্ম", {
        }},
        AvroPattern{"spl", "স্প্ল", {
        }},
        AvroPattern{"sk", "স্ক", {
        }},
        AvroPattern{"Sc", "শ্চ", {
        }},
        AvroPattern{"sT", "স্ট", {
        }},
        AvroPattern{"st", "স্ত", {
        }},
        AvroPattern{"sn", "স্ন", {
        }},
        AvroPattern{"sp", "স্প", {
        }},
        AvroPattern{"sf", "স্ফ", {
        }},
        AvroPattern{"sm", "স্ম", {
        }},
        AvroPattern{"sl", "স্ল", {
        }},
        AvroPattern{"sh", "শ", {
        }},
        AvroPattern{"Sc", "শ্চ", {
        }},
        AvroPattern{"St", "শ্ত", {
        }},
        AvroPattern{"Sn", "শ্ন", {
        }},
        AvroPattern{"Sm", "শ্ম", {
        }},
        AvroPattern{"Sl", "শ্ল", {
        }},
        AvroPattern{"Sh", "ষ", {
        }},
        AvroPattern{"s", "স", {
        }},
        AvroPattern{"S", "শ", {
        }},
        AvroPattern{"oo`", "ু", {
        }},
        AvroPattern{"oo", "ু", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "উ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "উ"},
        }},
        AvroPattern{"o`", "", {
        }},
        AvroPattern{"oZ", "অ্য", {
        }},
        AvroPattern{"o", "", {
            AvroRule{{
                AvroMatchRule{"prefix", "vowel", "", false},
                AvroMatchRule{"prefix", "exact", "o", true},
            }, "ও"},
            AvroRule{{
                AvroMatchRule{"prefix", "vowel", "", false},
                AvroMatchRule{"prefix", "exact", "o", false},
            }, "অ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "অ"},
        }},
        AvroPattern{"tth", "ত্থ", {
        }},
        AvroPattern{"t``", "ৎ", {
        }},
        AvroPattern{"TT", "ট্ট", {
        }},
        AvroPattern{"Tm", "ট্ম", {
        }},
        AvroPattern{"Th", "ঠ", {
        }},
        AvroPattern{"tn", "ত্ন", {
        }},
        AvroPattern{"tm", "ত্ম", {
        }},
        AvroPattern{"th", "থ", {
        }},
        AvroPattern{"tt", "ত্ত", {
        }},
        AvroPattern{"T", "ট", {
        }},
        AvroPattern{"t", "ত", {
        }},
        AvroPattern{"aZ", "অ্যা", {
        }},
        AvroPattern{"AZ", "অ্যা", {
        }},
        AvroPattern{"a`", "া", {
        }},
        AvroPattern{"A`", "া", {
        }},
        AvroPattern{"a", "া", {
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "আ"},
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"prefix", "exact", "a", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "য়া"},
            AvroRule{{
                AvroMatchRule{"prefix", "exact", "a", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "আ"},
        }},
        AvroPattern{"i`", "ি", {
        }},
        AvroPattern{"i", "ি", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ই"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ই"},
        }},
        AvroPattern{"I`", "ী", {
        }},
        AvroPattern{"I", "ী", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ঈ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ঈ"},
        }},
        AvroPattern{"u`", "ু", {
        }},
        AvroPattern{"u", "ু", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "উ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "উ"},
        }},
        AvroPattern{"U`", "ূ", {
        }},
        AvroPattern{"U", "ূ", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ঊ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ঊ"},
        }},
        AvroPattern{"ee`", "ী", {
        }},
        AvroPattern{"ee", "ী", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ঈ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "ঈ"},
        }},
        AvroPattern{"e`", "ে", {
        }},
        AvroPattern{"e", "ে", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "এ"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "exact", "`", true},
            }, "এ"},
        }},
        AvroPattern{"z", "য", {
        }},
        AvroPattern{"Z", "্য", {
        }},
        AvroPattern{"y", "্য", {
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", true},
                AvroMatchRule{"prefix", "punctuation", "", true},
            }, "য়"},
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "ইয়"},
        }},
        AvroPattern{"Y", "য়", {
        }},
        AvroPattern{"q", "ক", {
        }},
        AvroPattern{"w", "ও", {
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
                AvroMatchRule{"suffix", "vowel", "", false},
            }, "ওয়"},
            AvroRule{{
                AvroMatchRule{"prefix", "consonant", "", false},
            }, "্ব"},
        }},
        AvroPattern{"x", "ক্স", {
            AvroRule{{
                AvroMatchRule{"prefix", "punctuation", "", false},
            }, "এক্স"},
        }},
        AvroPattern{":`", ":", {
        }},
        AvroPattern{":", "ঃ", {
        }},
        AvroPattern{"^`", "^", {
        }},
        AvroPattern{"^", "ঁ", {
        }},
        AvroPattern{",,", "্‌", {
        }},
        AvroPattern{",", ",", {
        }},
        AvroPattern{"$", "৳", {
        }},
        AvroPattern{"`", "", {
        }},
    };
}
std::string makeVowels() { return "aeiou"; }
std::string makeConsonants() { return "bcdfghjklmnpqrstvwxyz"; }
std::string makeCaseSensitive() { return "oiudgjnrstyz"; }
